#ifndef __war3_hero_skill_viewer_frame__
#define __war3_hero_skill_viewer_frame__

/**
@file
Subclass of War3HeroSkillViewerFrameBase, which is generated by wxFormBuilder.
*/

#include "war3_hero_skill_viewer_frame_bse.h"

//// end generated include

#include <string>

#include <map>
#include <vector>

#include "../ini/SimpleIni.h"

namespace rco
{

struct SkillInfo
{
  std::wstring name;
  std::wstring research_uber_tip;

  void Clear() {
    name.clear();
    research_uber_tip.clear();
  }
};

struct HeroInfo
{
  std::wstring name;
  std::vector<SkillInfo> skill_info_vector;

  void Clear() {
    name.clear();
    skill_info_vector.clear();
  }
};

using HeroInfoPair = std::pair<std::wstring, HeroInfo>;
using HeroInfoMap = std::map<std::wstring, HeroInfo>;

/** Implementing War3HeroSkillViewerFrameBase */
class War3HeroSkillViewerFrame : public War3HeroSkillViewerFrameBase
{
protected:
  // Handlers for War3HeroSkillViewerFrameBase events.
  void SearchHeroTextCtrlOnText(wxCommandEvent& event) override;
  void HeroListBoxOnListBox(wxCommandEvent& event) override;
  void SkillListBoxOnListBox(wxCommandEvent& event) override;
  void OpenFileMenuItemOnMenuSelection(wxCommandEvent& event) override; 
  void Close_menuItem_OnMenuSelection(wxCommandEvent& event) override;
  void AboutMenuItemOnMenuSelection(wxCommandEvent& event) override;
public:
  /** Constructor */
  War3HeroSkillViewerFrame(wxWindow* parent);
  //// end generated class members

private:
  bool ParseHeroSkillListFile(const std::wstring& file_name);
  void CreateHeroInfoMap();
  void FillHeroListBox();
  void FillSkillListBox(const std::wstring &hero_name);

  CSimpleIni hero_skill_list_ini_;
  HeroInfoMap hero_info_map_;
  std::vector<std::wstring> research_uber_tip_vector_;
};

}; // end of namespace "rco"

#endif // __war3_hero_skill_viewer_frame__
